### ISSUE TITLE
GFX temperature shows "N/A"

### ISSUE THREAD

**Issue by erkexzcx** [daringer/asus-fan#54]
I noticed this issue when I reinstalled my Arch Linux system on my Asus N550JV notebook. I used to have configured script to automatically configure fan speeds according to GFX and CPU temperatures, but because I rarely used GFX and I did not monitor GFX temperatures anymore later - I am unaware why it does not work. From my understanding, one of these 2 reasons is why this doesn't work now, but used to work before:

- I reinstalled my OS and I forgot to configure something.
- You made some changes to asus_fan kernel module and now it does not work. (more likely I guess)

In the past, GFX temperature used to show +0.0°C (just 0c temp) when GPU is **not in use**. When I start any app with **optirun** or **primusrun** (forces to use GPU instead of CPU graphics) - GFX starts to show real temperature (e.g. +60.0°C). For now, it shows **N/A** all the time:
![screenshot_2017-08-27_14-59-08](https://user-images.githubusercontent.com/5955795/29749571-53b3aa4c-8b38-11e7-80f2-26b81ed71d2f.png)

In addition, according to Nvidia settings - GPU temperature sensor works, so no hardware related issues:
![gpu settings](https://user-images.githubusercontent.com/5955795/29749633-58476d04-8b39-11e7-9baa-973668c4b885.png)

And finally, I used https://aur.archlinux.org/packages/asus-fan-dkms-git/ script.

P.S. Let me know if you need anything from me - I am here to help :)

**Comment by daringer** [comment]
Obviously the gfx-temp(-data) is not within the same ACPI "slot" for your zenbook-model, if you find out where it actually resides within the ACPI world, someone (or I) can easily make sure that this one will be used (thus correctly outputted), instead of the "N/A".

you might use: 
* the [nbfc - tutorial](https://github.com/hirschmann/nbfc/wiki/Analyze-your-notebook%27s-DSDT)
* the `misc.asus_ec.pl` script (this might be easy by using `nvidia-settings` together with it, just make sure the temp value constantly changes, the identifying the right numbers might be easy)
* the internet :D
